---
# - name: Starting to install cyberchef
#   ansible.builtin.include_vars:
#     file: ../../../playbooks/vars/vault.yml
- name: Install cockpit
  ansible.builtin.apt:
      name: cockpit
      state: present
      update_cache: true
- name: Enable cockpit service
  ansible.builtin.systemd:
      name: cockpit
      enabled: true
      masked: false
- name: Make sure that config root exists
  ansible.builtin.file:
    path: "{{ config_root }}"
    state: directory
    mode: '777'
- name: Ensure directory structure exists on host
  ansible.builtin.file:
    path: '{{config_root}}config/{{ item.path }}'
    state: directory
    mode: '777'
  with_community.general.filetree: 'templates/config/'
  when: item.state == 'directory'
- name: Copy over the config files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ config_root }}config/{{item.path}}'
    mode: '777'
  with_community.general.filetree: 'templates/config/'
  when: item.state == 'file'
- name: Notice
  ansible.builtin.debug:
    msg: Note that cockpit is not accessable via its domain i am working to fix that