http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.{{ domain}}`)"
      entrypoints:
      - "websecure"
      service: nextcloud
      middlewares:
      - nextcloud-chain
      tls:
        certresolver: "{{ cert_provider }}"

  services:
    nextcloud:
      loadBalancer:
        servers:
        - url:  "http://nextcloud-aio-apache:11000"
 #       - url: "http://nextcloud-aio-domaincheck:11000" # Use the host's IP address if Traefik runs outside the host network
  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
        - "X-Forwarded-Host"
        referrerPolicy: "same-origin"

    https-redirect:
      redirectscheme:
        scheme: https

    nextcloud-chain:
      chain:
        middlewares:
        # - ... (e.g. rate limiting middleware)
        # - authelia@file
        - https-redirect
        - nextcloud-secure-headers
