- name: Make sure that project root exists
  ansible.builtin.file:
    path: "{{ project_root }}gitea"
    state: directory
    mode: '777'
- name: Make sure that config root exists
  ansible.builtin.file:
    path: "{{ config_root }}"
    state: directory
    mode: '777'
- name: Ensure directory structure exists on host
  ansible.builtin.file:
    path: '{{project_root}}/{{ item.path }}'
    state: directory
    mode: '777'
  with_community.general.filetree: 'templates/compose/'
  when: item.state == 'directory'
- name: Copy over the compose files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ project_root }}gitea/{{item.path}}'
    mode: '777'
  with_community.general.filetree: 'templates/compose/'
  when: item.state == 'file'
- name: Ensure directory structure exists on host
  ansible.builtin.file:
    path: '{{config_root}}config/{{ item.path }}'
    state: directory
    mode: '777'
  with_community.general.filetree: 'templates/config/'
  when: item.state == 'directory'
- name: Copy over the config files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ config_root }}config/{{item.path}}'
    mode: '777'
  with_community.general.filetree: 'templates/config/'
  when: item.state == 'file'
- name: Install Mysql Module for Python
  ansible.builtin.pip:
    name: PyMySQL
- name: Create gitea DB
  community.mysql.mysql_db:
    name: gitea
    login_user: root
    login_password: "{{mysql_root_pass}}"
    state: present
- name: Create DB User
  mysql_user:
    name: gitea
    password: "{{mysql_gitea_pass}}"
    priv: 'gitea.*:ALL'
    host: '%'
    state: present
    # login_host: localhost:3306
    login_user: root
    login_password: "{{mysql_root_pass}}"
- name: Create docker_default_network
  community.docker.docker_network:
    name: docker_default_network
- name: Start the stack
  community.docker.docker_compose:
    project_src: "{{project_root}}gitea/"
    restarted: true