providers: 
  file:
    directory: /etc/traefik
    watch: true
  docker:
    exposedByDefault: false
api:
  dashboard: true
  debug: true
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
certificatesResolvers:
  staging:
    acme:
      email: {{lets_encrypt_email}}
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: {{lets_encrypt_email}}
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
http:
  middlewares:
    default-security-headers:
    https-redirect:
      redirectScheme:
        scheme: https
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.{{domain}}"
        trustForwardHeader: true
        authResponseHeaders:
        - "Remote-User"
        - "Remote-Groups"
        - "Remote-Email"
        - "Remote-Name"
    default-headers:
      headers:
        frameDeny: false
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
          Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  serversTransports:
    disableSSLCheck:
      insecureSkipVerify: true
experimental:
  plugins:
    torblock:
      moduleName: "github.com/jpxd/torblock"
      version: "v0.1.1"
    themepark:
      moduleName: "github.com/packruler/traefik-themepark"
      version: "v1.2.2"

accessLog:
  filePath: "/var/log/traefik/access.log"
